### PR TITLE
NIH-RSV_MSIRS model submission

### PR DESCRIPTION
**Pull request by sunky1016**
First submission

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @sunky1016 ,

Thanks for the submission, it seems to be all good. I just wanted to verify that I understand correctly the numbering in the 2  columns: `stochastic_run`, and `run_grouping`. It seems that your model runs has 5 different run_grouping (grouped by scenario, location, age group and horizon) each with 20 different stochastic run (grouped by scenario, location, age group and horizon), am I correct? 

Please feel free to let me know if any issues or questions,

Many thanks,
Lucie

**Comment by sunky1016** [comment]
> Good morning @sunky1016 ,
> 
> Thanks for the submission, it seems to be all good. I just wanted to verify that I understand correctly the numbering in the 2 columns: `stochastic_run`, and `run_grouping`. It seems that your model runs has 5 different run_grouping (grouped by scenario, location, age group and horizon) each with 20 different stochastic run (grouped by scenario, location, age group and horizon), am I correct?
> 
> Please feel free to let me know if any issues or questions,
> 
> Many thanks, Lucie

Hi Lucie,

Thanks very much for checking. Yes, the run grouping id reflects 5 sub-scenarios (sub-models) with 5 different levels of NPI differences between children and adults range from 0 the strongest to 4 the weakest). The overall 100 runs are a pooled projection of sub-models with 20 runs from each sub-model.

**Comment by LucieContamin** [comment]
Thank you for the quick reply and the information, I looks all good, I will merge the PR.
Thanks again!

**Comment by sunky1016** [comment]
> Thank you for the quick reply and the information, I looks all good, I will merge the PR. Thanks again!

Thanks Lucie for your help with the submission!

All best,
Sunky

**Pull request merged**
