### PR TITLE
Submit Round 2 for USC-SIkJalpha

### PR DESCRIPTION
**Pull request by scc-usc**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @scc-usc ,

Thank you for your submission, I just wanted to verify some information:
- Pairing: paired by "scenario_id", "horizon", "location", "age_group", no stochasticity
- Projections: for 4 locations (Michigan (26), New Mexico (35), New York (36) and Oregon (41)), all projections are equal to zero for all age groups and scenarios. 
Is that expected?

Please let me know if any questions or issues,
Thanks,

Lucie

**Comment by scc-usc** [comment]
Yes, there is stochasticity. But the values for the locations should not be zero. I will check and resubmit.

**Comment by LucieContamin** [comment]
Thanks! 
If there is stochasticity, please update the `stochastic_run` column accordingly, I am happy to help if any questions or issues.

**Comment by scc-usc** [comment]
Sorry, I mistyped earlier. There is **no** stochasticity. 
I have fixed the issue with zero projections in the latest submissions.

**Review by LucieContamin — APPROVED** [review]

**Pull request merged**
