### PR TITLE
USC-SIkJalpha Updated Results

### PR DESCRIPTION
**Pull request by maa989**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @maa989,

Thank you for your update, It seems that the validation had an issue. It seems to be link to the format of multiple columns, they seem to be in a list format. Will it be possible to verify it please?

Please let me know if any issues or questions,
Best,
Lucie

**Comment by maa989** [comment]
Hello @LucieContamin, I think this updated file should fix the error. If not, please let me know which columns have the wrong format. 

Thanks.

Best,
Majd.

**Comment by LucieContamin** [comment]
Hello @maa989 , It seems that the validation seems to have encounter some issues with the output type id column:
- the format is character (which you seem to already have) but it seems that some quantiles have an additional whitespace (for example: `" 0.05"`, `"  0.1"`,  `" 0.15"`) and your "NA" value is not registered as a NA value ("nan" instead).

Please let me know if any issues or questions,
Best,
Lucie

**Comment by maa989** [comment]
Hi @LucieContamin, please let me know if there are still any issues. Thanks.

**Comment by LucieContamin** [comment]
Hi @maa989 ,

Sorry I still see the same kind of problem:
```
 [1] "NaN"          "1.000000e-02" "2.500000e-02" "5.000000e-02" "1.000000e-01" "1.500000e-01"
 [7] "2.000000e-01" "2.500000e-01" "3.000000e-01" "3.500000e-01" "4.000000e-01" "4.500000e-01"
[13] "5.000000e-01" "5.500000e-01" "6.000000e-01" "6.500000e-01" "7.000000e-01" "7.500000e-01"
[19] "8.000000e-01" "8.500000e-01" "9.000000e-01" "9.500000e-01" "9.750000e-01" "9.900000e-01"
```
The "NA" value is all good in the horizon, run_grouping and stochastic_run columns

The quantile should be equal to:
```
0.010 0.025 0.050 0.100 0.150 0.200 0.250 0.300 0.350 0.400 0.450 0.500
0.550 0.600 0.650 0.700 0.750, 0.800 0.850 0.900 0.950 0.975 0.990 
```
Please let me know if any issues or questions,
Best,
Lucie

**Comment by maa989** [comment]
Hi again @LucieContamin , I believe the issue with the quantiles is resolved now. But the issue might still remain with the "NA" value. This value is of type NaN (or NA) as it is in the horizon, run_grouping and stochastic_run columns (which work). But when writing to a parquet file, each column entry must have the same data type as all other column entries. 

Which is why in the output_type_id, i can not leave it as NaN and actually have to convert it to a character (as the rest). This was working before when i had the values explicitly set to "nan". Should i just explicitly set these values to "NA" if it does not work this time?

**Pull request merged**
