### PR TITLE
PSI-PROF 2024-25 submission

### PR DESCRIPTION
**Pull request by jturtle**
We are submitting only hospitalizations. Trajectories are paired across horizon, age, and scenario. There is no stochasticity, so stochastic_run matches run_grouping. Let us know if anything looks off.

### CODE REVIEW

**Comment by jturtle** [comment]
Oops, value rounding continues to fail to propagate from round-to-round in my submission codes.  I have changed the code and am re-processing the submission with rounded trajectory values.  I can re-submit, but I don't think that helps your storage issue.

**Comment by LucieContamin** [comment]
Good morning,

Thank you for the submission, I can ignore the rounding issue for now. Thanks for the information, I just have a small remark: if you have no stochasticity, the column `stochastic_run` should be set to 1. 
Please see the [documentation](https://scenariomodelinghub.org/documentation/sample_format.html):

> If each model run is not stochastic, the column will be set to a unique identifier: 1 for all rows. 

Please let me know if any issues or questions,
Thanks,

Lucie

**Review by LucieContamin — COMMENTED** [review]
Good morning,

Thank you for the submission, I can ignore the rounding issue for now. 

Thanks for the information, I just have a small remark: if you have no stochasticity, the column stochastic_run should be set to 1.
Please see the [documentation](https://scenariomodelinghub.org/documentation/sample_format.html):
> If each model run is not stochastic, the column will be set to a unique identifier: 1 for all rows.

Please let me know if any issues or questions,
Thanks,

Lucie

**Review by LucieContamin — APPROVED** [review]
Thank you for the update

**Pull request merged**
