### PR TITLE
RSV Round 2 submission

### PR DESCRIPTION
**Pull request by lunarmouse**
Team: UNCC
Model: Hierbin

### CODE REVIEW

**Comment by lunarmouse** [comment]
Hi Lucie, hope you have had a nice Thanksgiving break! I am trying to submit to RSV Round #2 but I kept getting error messages on misspelled column names. Since this is the first time that I work with RSV SMH, could you please let me know the correct column names? I tried to look for it on the GitHub information site but was not able to locate it. In addition, are there any specific format for specifying the age groups? Currently I am using "0-0.99", "1-4", "5-64", "65-130", and "0-130" but I don't know if this is the required format. Thanks very much for your help!

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thanks for your submission! I looked at your pull-request and there is some issues that might explain the validation problem:
- For the projection file (parquet file):
     - `origin_date` and the date in the filename should match and be equal to the projection starting date: `"2027-04-28"` for this round
     - the `output_type_id` column should be equal to `NA` for the "sample" output type and the pairing information should be filled in two additional column: `run_grouping` and `stochastic_run`.  Please find [here](https://scenariomodelinghub.org/documentation/sample_format.html) some documentation on these columns. 
- For the abstract (md file):
    - The file should be stored in the `model-abstract/` folder and should be name `"2027-04-28-UNCC-hierbin.md"`.
    - It should also match the [template](https://github.com/midas-network/rsv-scenario-modeling-hub/blob/main/model-abstract/template/2024-07-28.md) file, with the `FILL` replaced with your results/information for this round.
    - Please find some documentation [here](https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/model-abstract)
- For the metadata file (yaml file):
   - As it's your first participation to the RSV round, you need to also provide a metadata file. It should be stored in the `model-metadata` folder. Please find some documentation and example, [here](https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/model-metadata)
   
Please let me know if any questions or other issues,
Best,
Lucie

**Comment by lunarmouse** [comment]
Thanks very much for your quick response, Lucie! I will get them fixed tonight and send a new pull request. Have a good one.

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for the update, the validation had an error yesterday, it has been fixed. I apologize for the inconvenience. I triggered a new validation this morning. It seems that it did not worked properly because of an issue in the `scenario_id` column. Once the column is fixed, the output of the validation should be fixed and easier to read. 

Please let me know if any questions or issues,
Best,

Lucie

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

Thank you for the update, the validation had an error because the path of the file is not in the expected format so it can not run properly.
- The projection file should be: `model-output/UNCC-hierbin/2024-07-28-UNCC-hierbin.gz.parquet`

Also I cannot merge your file without an associated metadata file:
- the should be stored and called as: `model-metadata/UNCC-hierbin.yaml` (please see the documentation [here](https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/model-metadata))

Also as a reminder for this round:
- the origin date and the date in name of the file is: `"2024-07-28"`
- the scenario id are: `"A-2024-09-20"`, `"B-2024-09-20"`, `"C-2024-09-20"`, `"D-2024-09-20"`,` "E-2024-09-20"`

Please let me know if any questions or issues,
Best,

Lucie

**Comment by LucieContamin** [comment]
Hi @lunarmouse ,

THanks for the update, I am looking into the Validation output. In the meantime, I noticed an issue with the filename. If the metadata and folder name used the `model_abbr: "Hierbin"`, than all the filenames should follow the same name with the same upper/lower case rules. So the file should be named:
`"model-output/UNCC-Hierbin/2024-07-28-UNCC-Hierbin.gz.parquet"`

I will keep you inform for the validation output. 
Please let me know if any questions or issues,
Best,

Lucie

**Review by LucieContamin — APPROVED** [review]
Hi @lunarmouse ,

Thank you for the update, it looks all good now. I just wanted to verify that I understand the pairing correctly:
- 13 groups in `run_grouping`, 1 per location
- For each run_grouping group, 100 `stochatic_run` paired by scenario, age group and horizon

Is that correct? 
Best, Lucie

**Pull request merged**
