### PR TITLE
CEPH Round 02

### PR DESCRIPTION
**Pull request by paulocv**
Here is our submission for the SMH round 2, including minor changes to the metadata. 
Feel free to use the comments to let us know about any issues with the files.

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @paulocv ,

Thank you for the submission, it looks like there is an issue with your submission file. I try to load it, and arrow package returns an error:
`Error: Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.`

Would it be possible to verify it, please?

Please let me know if any questions or issues,
Best, Lucie

**Comment by paulocv** [comment]
Hi @LucieContamin 

Thank you for checking. Have you tried to decompress the file first? Since the flat `.parquet` file exceeds the 25Mb limit imposed by GitHub, and as suggested in the [Data Submission Instructions](https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/model-output#data-submission-instructions), I submitted a gzip-compressed file. 

I was able to reproduce your error message in `pyarrow` by trying to directly read the file without decompressing, but the decompressed file produced by running (on a unix OS):

```
gzip -dk 2024-07-28-CEPH-MetaRSV.parquet.gz
``` 

opens without problems.

**Comment by LucieContamin** [comment]
Hi @paulocv ,

Thank you for the answer, and the information.
To add on your comment, you should be able to by-pass the 25Mb limit by using git/github (command line), in this case the hard-limit is 100 Mb. I am happy to help if necessary.

For the compression file, would it be possible to compress it with pyarrow so I can open it with arrow, please? Arrow can normally open compress files. (https://arrow.apache.org/docs/python/parquet.html#compression-encoding-and-file-compatibility)
For example, for python:
```
import pyarrow.parquet as pq
pq.write_table(table, where, compression='gzip')
```
The loading process of all the data use arrow packages, so it's important to be able to read it with it. Does that make sense?

Please let me know if any questions or issues,
Best, Lucie

**Comment by paulocv** [comment]
Hi @LucieContamin 

Thank you for the instructions, I was able to create the `.gz.parquet` file directly from pyarrow, as you instructed.

I will clone the repo and submit using git, which I hadn't done so far to avoid cloning the entire repo to my computer.

**Comment by LucieContamin** [comment]
Thank you for the update, 
I totally understand the problem with cloning the full repository, maybe a sparse-checkout might help? 

Best, Lucie

**Review by LucieContamin — APPROVED** [review]
Thanks for the submission, I just made a small comment on the metadata file, but it does not block the PR.

Please feel free to let me know if any questions or issues, 
Best, Lucie

**Comment by paulocv** [comment]
Thank you @LucieContamin . I removed any trailing commas from the YAML elements.

**Pull request merged**
