### PR TITLE
CU submission

### PR DESCRIPTION
**Pull request by tkcy**

### CODE REVIEW

**Comment by tkcy** [comment]
@LucieContamin added metadata!

**Comment by LucieContamin** [comment]
Hi @tkcy ,

I just wanted to verify the "sample" run_grouping and stochastic_run columns information if that's ok. It seems that each model run has a `run_grouping` set grouped by `age_group`, `horizon`,` scenario_id` replicated in multiple stochastic run. The different scenarios are assumed to share the same stochastic runs. Is that correct?

Please feel free to let me know if any issues or questions,

Thanks,
Lucie

**Comment by LucieContamin** [comment]
Hi Teresa,

Thank you very much for the quick answer and for the explanation, I agree that the format you use is the best option to represent it
Thanks,
Lucie

**Comment by tkcy** [comment]
@LucieContamin Hi! just a heads up that we're trying out a slightly altered version of the model where we fit the model once and then apply the different interventions after the fitting is complete in order to better isolate the effects of the interventions. This should be ready in the next day or two. Thanks!

**Comment by LucieContamin** [comment]
Hi @tkcy ! Thank you for letting me know!

**Pull request merged**
