### PR TITLE
update CU model 

### PR DESCRIPTION
**Pull request by tkcy**
all model fitting is now done prior to applying any interventions, thus differences in simulated outcomes are due to the applied interventions.

### CODE REVIEW

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for the update, I just have a minor issues: for the `"origin_date"` column, it seems that when I load the data this column on my local is set to a date with a timestamp and timezone, will it be possible to restrict the date to a "day" unit or set it to a character format to avoid issue?

Please let me know if any questions,
Thanks,
Lucie

**Comment by LucieContamin** [comment]
It also seems that your PR contains lot of changes on other files, would it be possible to update your fork to avoid that issue?

Thanks again,
Lucie

**Comment by tkcy** [comment]
@LucieContamin sorry about that, i think it's fixed now?

**Comment by LucieContamin** [comment]
Hi @tkcy ,

Thank you for the update, it seems that I still have the "origin_date" column issue, it seems that when I load the data this column on my local is set to a date with a timestamp and timezone (for example: `"2023-11-11 19:00:00"` instead of `"2023-11-12"` , will it be possible to restrict the date to a "day" unit and/or set it to a character format to avoid issue?

Please let me know if any questions,
Thanks,
Lucie

**Comment by LucieContamin** [comment]
Good morning @tkcy ,

I apologize if I was confusing, for the origin data column, you might be able to solve the issue by forcing the column to character containing the value: `"2023-11-12"`. 
Please let me know if any issues or questions, 

Many thanks, 
Lucie

**Comment by tkcy** [comment]
Trying again.

It's very strange, I'm only giving it the year, month and day and that's all I see on my end so I have no idea where it's picking up the timezone info!  Did the original file have the same issue?

**Comment by LucieContamin** [comment]
It seems to be all good now, thank you very much for the updates. The previous file had the same mistake but I miss it.  I am working on it, I apologize for the inconvenience.

Thanks, Lucie

**Pull request merged**
