### PR TITLE
CEPH projections

### PR DESCRIPTION
**Pull request by paulocv**

### CODE REVIEW

**Comment by LucieContamin** [comment]
HI @paulocv ,

Thank you very much for the submission and the update, I will process it soon. It looks all good, I just have a quick question to verify that I understand correctly the "sample" ID numbering information in your projections: the only difference between each run is stochasticity (`run_grouping` all 1) and the stochastic runs are grouped by scenario, location, horizon, age group, is that correct?

Please feel free to let me know if any questions or issues,
Many thanks,

Lucie

**Comment by paulocv** [comment]
Hi @LucieContamin, thank you for checking our files.
Yes, that is correct. All runs differ only by stochasticity, and we have no further grouping criteria to consider as `run_grouping`.

**Comment by paulocv** [comment]
Hi @LucieContamin, just a friendly check about this pull request: I believe it should be merged so that our model is considered in the analysis of this round, right?

**Comment by LucieContamin** [comment]
Hi @paulocv, thanks for your message. 

I will merge your PR, you are correct, the submission was accepted and it will be integrated in the round. The update was not run yet, as soon as it is, I will merge the PR. It should be all done in the next days, I apologize for the delay.

Please feel free to let me know if any other questions or issues,
Best,
Lucie

**Pull request merged**
