### PR TITLE
MOBS submission

### PR DESCRIPTION
**Pull request by jessica-davis**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @jessica-davis ,

Thank you for your submission! The content of the file seems to be all good, however the filename name and metadata file seems to have some small issues:
- the projection file should be in the format "YYYY-MM-DD-[team_abbr]-[model_abbr]" with a "-" after the date and the same `team_abbr` and `model_abbr `information as in the metadata file 
- the `team_abbr` in the metadata file should match the name in all the file and folder

In this case either:
- all the filenames and folder names need to be modified to "MOBS-GLEAM_RSV" and the projection file "2023-11-12-MOBS-GLEAM_RSV.gz.parquet"
OR
- the metadata file  `team_abbr` needs to be modified to "MOBS_NEU" and the projection file "2023-11-12-MOBS_NEU-GLEAM_RSV.gz.parquet".

Please feel free to let me know if any questions or issues,

Many thanks,
Lucie

**Comment by LucieContamin** [comment]
Also, I apologize for the double message, but I wanted to verify I understand correctly the numbering in the 2 new columns: stochastic_run, and run_grouping. It seems that your model runs has different run_grouping (model run independent) for every stochastic run, grouped by age group and horizon. Like the example 2 in the wiki page (https://github.com/midas-network/rsv-scenario-modeling-hub/wiki/Sample-File-Format#example-2-grouped-by-age_group-and-horizon). Is that correct?

Please feel free to let me know if any questions or issues,

Many thanks,
Lucie

**Comment by jessica-davis** [comment]
Hi Lucy, I'm sorry for the errors. I have fixed the names, please let me know if there are any other issues. 
I was also confused on how I should use the stochastic_run and run_grouping columns and I copied what I saw in a test file so if there is a better way to format this let me know. Essentially all I want to group together are the age groups from the same trajectory. The trajectories are not connected across scenarios and locations because they were calibrated and ran independently.

**Comment by LucieContamin** [comment]
Hi @jessica-davis ,
Thank you for the update and the quick reply.
For the submissions and filenames, it looks all good now. The visualization error message is on my side, I will try to fix it for next round, I apologize about that.
For the ID of the trajectories, the current format seems to match your description so no update needed.

Thanks again, I will merge the PR.
Best, Lucie

**Pull request merged**
