### PR TITLE
Submit NotreDame-FRED round 1 RSV projections

### PR DESCRIPTION
**Pull request by mooresea**

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @mooresea ,

Thank you very much for your submission. 
Would it be possible to also provide a metadata file with your first submission, please?
The file should be in a yaml format in the `model-metadata` folder, please find here some documentation and examples files: https://github.com/midas-network/rsv-scenario-modeling-hub/tree/main/model-metadata

Please feel free to let me know if any issues or questions,

Thanks,
Lucie

**Comment by LucieContamin** [comment]
Hi @mooresea ,

Thank you for the quick update, I just wanted to verify some metadata information if that's ok.
- The `team_abbr` and `model_abbr` should be used in all the file names. I updated the documentation accordingly. So in your case, either the `team_abbr` should be `NotreDame` and the `model_abbr` should be `FRED` (accepted to have same abbreviation and name) OR all your folder and files should be with the `team-model` name: `UND-fred`.  

> Each sub-directory within the [model-metadata/](https://github.com/midas-network/rsv-scenario-modeling-hub/blob/main/model-metadata) directory has the format:
> 
> `team-model`
> 
> where
> 
>     `team` is the abbraviated teamname (`team_abbr`) and
>     `model` is the abbreviated name of your model (`model_abbr`).
> 
> Both team and model should be less than 15 characters, and not include hyphens nor spaces.
> 
> The team-model should correspond to the team-model sub-directory in the associated model-output folder containing the associated projections.
 
And just some additional information: 
  
- For the model contributors section, it will be used on the website so if you want to use your full first and last name or any different format (compared to the examples), it is accepted. I will use on the website the same format as provided in the metadata. 

- Also the `team-funding`, `data_inputs`, `methods_long` and `citation` are optional additional field so if you don't have to provide them all. For example, it seems that you don't have a citation so please feel free to remove it from the yaml file. 

Please feel free to let me know if any issues or questions,

Thanks,
Lucie

**Comment by mooresea** [comment]
@LucieContamin I have edited both our team's projections and the metadata file. Regarding the run_grouping, the trajectories are grouped by age_group, horizon, scenario_id, and location. The model is stochastic, but I ran 100 trajectories for each of these groupings, but the parameter values were drawn from a joint posterior each time. So some of the 100 trajectories have the same parameter values and some don't. I don't have the computational bandwidth to run 100 trajectories for each parameter combination, nor would it make sense to do so since I draw from the posterior based on the likelihood, so more likely parameter combination should be selected more frequently and contribute more to the mean projections. That is why I set 'stochastic_run=1' for each trajectory even though there is model stochasticity.

**Comment by LucieContamin** [comment]
thanks for the updates

**Pull request merged**
