### PR TITLE
UVA submission

### PR DESCRIPTION
**Pull request by chenj-uva**
UVA-EpiHiperRSV model submission for Round 1.

### CODE REVIEW

**Comment by LucieContamin** [comment]
Good morning @chenj-uva,

Thank you for your submission, I just wanted to verify the "sample" run_grouping and stochastic_run columns. It seems that each model run has a different run_grouping and stochastic_run set grouped by age_group, horizon , scenario_id and location, is it correct?

Please feel free to let me know if any questions or issues,
Best, 
Lucie

**Comment by LucieContamin** [comment]
Also, I noticed that your "age_group" column was in a "factor" format, would it be possible to change it to a character format, please?

Please feel free to let me know if any questions or issues,
Thanks,
Lucie

**Comment by chenj-uva** [comment]
@LucieContamin ,
I was confused about run_grouping and stochastic_run. Thank you for pointing it out. I have fixed it. I've also changed the format of age_group column.

**Comment by LucieContamin** [comment]
@chenj-uva ,
Thank you for the update! For the 2 new columns, I am happy to provide more information if necessary. You previous format was accepted, I just wanted to verify that I was understanding it correctly.
It seems that in your last version:
- `run_grouping` is all equal to 1
- `stochastic_run`: group by scenario, age_group, location, horizon. 

This format is also accepted and as I understand, it seems that the only difference between each run is stochasticity and the stochastic runs are grouped by scenario, location, horizon, age group. Do I understand correctly?

Thanks,
Lucie

**Pull request merged**
